version: '2.1'
services:
  academy-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      STUDENT_URL: '192.168.99.101'
      STUDENT_PORT: '3001'
      STUDENT_ENTRY: 'students-ms/resources/students'
    ports:
      - '5000:5000'
